[package]
name = "mev"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
ed25519-dalek = "2"
sha2 = "0.10"
hex = "0.4"
thiserror = "1.0"
bincode = "1.3"
