[package]
name = "rollup"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
execution = { path = "../execution" }
zk = { path = "../zk" }
da = { path = "../da" }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
