[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
sled = "0.34"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
serde_json = "1.0"
tempfile = "3"
bincode = "1.3"
anyhow = "1.0"

[dev-dependencies]
tempfile = "3"
