[chain]
chain_id = "modular-testnet-1"
timestamp = 1700000000
initial_height = 0

[consensus]
block_time_ms = 3000
max_validators = 100
min_stake = "100000"

[governance]
proposal_deposit = "1000"
voting_period_blocks = 1000
quorum_threshold = "0.334"

[[validators]]
address = "0x1111111111111111111111111111111111111111"
stake = "1000000"
commission_rate = "0.10"
public_key = "401c76b85552dfd28fd120e236b252b4eb7f45ef6b72d3103ea0082fbb476642"

[[validators]]
address = "0x2222222222222222222222222222222222222222"
stake = "800000"
commission_rate = "0.10"
public_key = "9f140c78dec55de6a777baa88ba33e65d0d7e46243557169f8b827f725392acc"

[[validators]]
address = "0x3333333333333333333333333333333333333333"
stake = "600000"
commission_rate = "0.10"
public_key = "ec77526bdb058b2684570107a3581ccfe8cec4e03dfd5ac409213f181e66b93a"

[[accounts]]
address = "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
balance = "10000000000"

[[accounts]]
address = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
balance = "5000000000"
