global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'validator1'
    static_configs:
      - targets: ['validator1:9090']

  - job_name: 'validator2'
    static_configs:
      - targets: ['validator2:9090']

  - job_name: 'validator3'
    static_configs:
      - targets: ['validator3:9090']

  - job_name: 'rpc1'
    static_configs:
      - targets: ['rpc1:9090']

  - job_name: 'rpc2'
    static_configs:
      - targets: ['rpc2:9090']
