[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
ed25519-dalek = { version = "2.0", features = ["serde"] }
anyhow = "1.0"
serde_json = "1.0"
rand = "0.8"
